/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.olta.crm.view.admin;

import com.olta.crm.work.AssignWorkI;
import com.olta.crm.work.AssignWorkImpl;
import java.awt.HeadlessException;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author Olti
 */
public class AssignWork extends javax.swing.JFrame {

    /**
     * Creates new form AssignWork
     */
    public AssignWork() {
        initComponents();
        setLocationRelativeTo(null);

    }
    private HomeAdmin home;
    private final AssignWorkI assignWork = new AssignWorkImpl();

    public JLabel getUser_name() {
        return user_name;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        user_name = new javax.swing.JLabel();
        back = new javax.swing.JButton();
        text = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        project_name = new javax.swing.JTextField();
        project_issue = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        task_number = new javax.swing.JTextField();
        type_of_procces = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        assign_work = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        err_fiel_RI = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        worker_name = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        descr = new javax.swing.JEditorPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(45, 118, 232));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        user_name.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        user_name.setForeground(new java.awt.Color(255, 255, 255));
        user_name.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(user_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 30, 290, 30));

        back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/back.png"))); // NOI18N
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        jPanel1.add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 67, 48));

        text.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        text.setForeground(new java.awt.Color(255, 255, 255));
        text.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        text.setText("Assign Work");
        jPanel1.add(text, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 30, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1040, 70));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        project_name.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        project_name.setForeground(new java.awt.Color(102, 102, 102));
        project_name.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(12, 91, 160)));
        jPanel2.add(project_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 260, 284, -1));

        project_issue.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        project_issue.setForeground(new java.awt.Color(102, 102, 102));
        project_issue.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(12, 91, 160)));
        jPanel2.add(project_issue, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 390, 284, -1));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(102, 102, 102));
        jLabel11.setText("Assign Work To");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 60, 216, -1));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(153, 153, 153));
        jLabel12.setText("Worker Name");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 120, 140, -1));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(153, 153, 153));
        jLabel13.setText("Project Issue");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 340, 146, 30));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(153, 153, 153));
        jLabel14.setText("Task Number ");
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 470, 135, -1));

        task_number.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        task_number.setForeground(new java.awt.Color(102, 102, 102));
        task_number.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(12, 91, 160)));
        jPanel2.add(task_number, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 520, 284, -1));

        type_of_procces.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        type_of_procces.setForeground(new java.awt.Color(102, 102, 102));
        type_of_procces.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(12, 91, 160)));
        type_of_procces.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                type_of_proccesActionPerformed(evt);
            }
        });
        jPanel2.add(type_of_procces, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 150, 241, -1));

        jLabel23.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(153, 153, 153));
        jLabel23.setText("Project Name");
        jPanel2.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 210, 140, 34));

        assign_work.setBackground(new java.awt.Color(45, 118, 232));
        assign_work.setFont(new java.awt.Font("Times New Roman", 2, 18)); // NOI18N
        assign_work.setForeground(new java.awt.Color(102, 102, 102));
        assign_work.setText("Send");
        assign_work.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                assign_workActionPerformed(evt);
            }
        });
        jPanel2.add(assign_work, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 490, 240, 58));

        jLabel16.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(153, 153, 153));
        jLabel16.setText("Description ");
        jPanel2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 230, 130, 34));

        err_fiel_RI.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        err_fiel_RI.setForeground(new java.awt.Color(255, 0, 0));
        jPanel2.add(err_fiel_RI, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 540, 284, 29));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 0, 0));
        jLabel1.setText("*");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 160, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 0, 0));
        jLabel2.setText("*");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 380, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 0, 0));
        jLabel3.setText("*");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 260, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 0, 0));
        jLabel4.setText("*");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 510, -1, -1));

        worker_name.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        worker_name.setForeground(new java.awt.Color(102, 102, 102));
        worker_name.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(12, 91, 160)));
        jPanel2.add(worker_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 160, 284, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 0, 0));
        jLabel5.setText("*");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 150, -1, -1));

        jLabel17.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(153, 153, 153));
        jLabel17.setText("Type of Procces");
        jPanel2.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 110, 130, 34));

        jScrollPane1.setViewportView(descr);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 270, 420, 200));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 1040, 620));

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        home = new HomeAdmin();
        home.setVisible(true);
        home.getWelcome_user().setText(user_name.getText());
        this.dispose();
    }//GEN-LAST:event_backActionPerformed

    private void assign_workActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_assign_workActionPerformed
        String workerName = worker_name.getText().trim();
        String projectName = project_name.getText().trim();
        String projectIssue = project_issue.getText().trim();
        String taskNumber = task_number.getText().trim();
        String typeOfWork = type_of_procces.getText().trim();
        int compelted = 0;
        String description = descr.getText().trim();

        assingWorkWithCallBAck(workerName, projectName, projectIssue, taskNumber, typeOfWork, compelted, description);

    }//GEN-LAST:event_assign_workActionPerformed

    private void assingWorkWithCallBAck(String workerName, String projectName, String projectIssue, String taskNumber, String typeOfWork, int compelted, String description) throws HeadlessException {
        if (workerName.isEmpty() || projectName.isEmpty() || projectIssue.isEmpty() || taskNumber.isEmpty() || typeOfWork.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please Enter the required field");
        } else {
            try {
                if (assignWork.assignWorkToUser(user_name.getText(), projectName, projectIssue, Integer.parseInt(taskNumber), typeOfWork, compelted, description)) {
                    worker_name.setText("");
                    project_name.setText("");
                    project_issue.setText("");
                    task_number.setText("");
                    type_of_procces.setText("");
                    descr.setText("");
                }
                
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(null, "Task Number should be number");
            }
        }
    }

    private void type_of_proccesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_type_of_proccesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_type_of_proccesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AssignWork.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AssignWork.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AssignWork.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AssignWork.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AssignWork().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton assign_work;
    private javax.swing.JButton back;
    private javax.swing.JEditorPane descr;
    private javax.swing.JLabel err_fiel_RI;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField project_issue;
    private javax.swing.JTextField project_name;
    private javax.swing.JTextField task_number;
    private javax.swing.JLabel text;
    private javax.swing.JTextField type_of_procces;
    private javax.swing.JLabel user_name;
    private javax.swing.JTextField worker_name;
    // End of variables declaration//GEN-END:variables
}
