/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.olta.crm.view.admin;

import com.olta.crm.manageuser.ManageUserImpl;
import com.olta.crm.manageuser.ManageUserIn;
import javax.swing.JLabel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Olta
 */
public class ManageUser extends javax.swing.JFrame {

    /**
     * Creates new form ManageUser
     */
    public ManageUser() {
        initComponents();
        setLocationRelativeTo(null);
        manageUser();
    }

    private HomeAdmin home;
    private ManageUserIn manage = new ManageUserImpl();

    public JLabel getUser_name() {
        return user_name;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        user_name = new javax.swing.JLabel();
        back = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelOfUser = new javax.swing.JTable();
        delete = new javax.swing.JButton();
        update = new javax.swing.JButton();
        last_name = new javax.swing.JTextField();
        email = new javax.swing.JTextField();
        role = new javax.swing.JTextField();
        phone = new javax.swing.JTextField();
        frist_name = new javax.swing.JTextField();
        id_card = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(45, 118, 232));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        user_name.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        user_name.setForeground(new java.awt.Color(255, 255, 255));
        user_name.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(user_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 30, 265, 30));

        back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/back.png"))); // NOI18N
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        jPanel1.add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 67, 48));

        jLabel16.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("Manage User");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(133, 29, 190, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1150, 80));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tabelOfUser.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Email", "Id Card", "Role", "Phone", "First Name", "Last Namel"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabelOfUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelOfUserMouseClicked(evt);
            }
        });
        tabelOfUser.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tabelOfUserKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(tabelOfUser);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 30, 930, 449));

        delete.setBackground(new java.awt.Color(255, 255, 255));
        delete.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        delete.setForeground(new java.awt.Color(0, 102, 255));
        delete.setText("Delete User");
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });
        jPanel2.add(delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 500, 168, 51));

        update.setBackground(new java.awt.Color(255, 255, 255));
        update.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        update.setForeground(new java.awt.Color(0, 102, 255));
        update.setText("Update User");
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });
        jPanel2.add(update, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 500, 168, 51));

        last_name.setText("Last Name");
        jPanel2.add(last_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 440, 160, 30));

        email.setText("email");
        jPanel2.add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 160, 30));

        role.setText("Role");
        role.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                roleActionPerformed(evt);
            }
        });
        jPanel2.add(role, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 160, 30));

        phone.setText("Phone");
        jPanel2.add(phone, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, 160, 30));

        frist_name.setText("First Name");
        jPanel2.add(frist_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 360, 160, 30));

        id_card.setText("Id Card");
        jPanel2.add(id_card, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 144, 160, 30));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 1150, 580));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        home = new HomeAdmin();
        home.setVisible(true);
        home.getWelcome_user().setText(user_name.getText());
        this.dispose();
    }//GEN-LAST:event_backActionPerformed

    private void tabelOfUserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelOfUserMouseClicked
        int selectedRow = tabelOfUser.getSelectedRow();
        email.setText(tabelOfUser.getValueAt(selectedRow, 0).toString());
        id_card.setText(tabelOfUser.getValueAt(selectedRow, 1).toString());
        role.setText(tabelOfUser.getValueAt(selectedRow, 2).toString());
        phone.setText(tabelOfUser.getValueAt(selectedRow, 3).toString());
        frist_name.setText(tabelOfUser.getValueAt(selectedRow, 4).toString());
        last_name.setText(tabelOfUser.getValueAt(selectedRow, 5).toString());
    }//GEN-LAST:event_tabelOfUserMouseClicked

    private void tabelOfUserKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tabelOfUserKeyPressed

    }//GEN-LAST:event_tabelOfUserKeyPressed

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
        if (!email.getText().equals("email")) {
            if (manage.deleteUser(id_card.getText())) {
                manageUser();
                setTextToEmpty();
            }
        }
    }//GEN-LAST:event_deleteActionPerformed

    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
        if (!email.getText().equals("email")) {
            if (manage.updateUserAdmin(email.getText(), id_card.getText(), Integer.parseInt(role.getText()), phone.getText(), frist_name.getText(), last_name.getText())) {
                manageUser();
                setTextToEmpty();
            }
        }
    }//GEN-LAST:event_updateActionPerformed

    private void setTextToEmpty() {
        email.setText("");
        id_card.setText("");
        role.setText("");
        phone.setText("");
        frist_name.setText("");
        last_name.setText("");
    }

    private void roleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_roleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_roleActionPerformed

    private void manageUser() {

        DefaultTableModel tableModel = configTable();

        Object[] row = new Object[6];

        //Impllement The user Var
        for (int i = 0; i < manage.getAllUsers().size(); i++) {
            row[0] = manage.getAllUsers().get(i).getEmail();
            row[1] = manage.getAllUsers().get(i).getIdCard();
            row[2] = manage.getAllUsers().get(i).getRole();
            row[3] = manage.getAllUsers().get(i).getPhone();
            row[4] = manage.getAllUsers().get(i).getFirstName();
            row[5] = manage.getAllUsers().get(i).getLastName();
            tableModel.addRow(row);
        }
        tabelOfUser.setModel(tableModel);

    }

    private DefaultTableModel configTable() {
        DefaultTableModel tableModel = new DefaultTableModel(
                new Object[][]{{}},
                new Object[]{"Email", "Id Card", "Role", "Phone", "First Name", "Last Name"}
        ) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }

        };
        tableModel.setRowCount(0);
        return tableModel;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManageUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManageUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManageUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManageUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManageUser().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private javax.swing.JButton delete;
    private javax.swing.JTextField email;
    private javax.swing.JTextField frist_name;
    private javax.swing.JLabel id_card;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField last_name;
    private javax.swing.JTextField phone;
    private javax.swing.JTextField role;
    private javax.swing.JTable tabelOfUser;
    private javax.swing.JButton update;
    private javax.swing.JLabel user_name;
    // End of variables declaration//GEN-END:variables
}
