/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.olta.crm.view.admin;

import com.olta.crm.myhours.Hours;
import com.olta.crm.myhours.MyHoursImpl;
import javax.swing.JLabel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Olti
 */
public class WorkesHours extends javax.swing.JFrame {

    /**
     * Creates new form WorkesHours
     */
    public WorkesHours() {
        initComponents();
        setLocationRelativeTo(null);
        manageHouers();

    }
    private HomeAdmin home;
    private Hours hours = new MyHoursImpl();

    public JLabel getUser_name() {
        return user_name;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        user_name = new javax.swing.JLabel();
        back = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        task_number = new javax.swing.JLabel();
        completed = new javax.swing.JLabel();
        type_of_project = new javax.swing.JLabel();
        project_issue = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelOfHouers = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        description = new javax.swing.JTextArea();
        user = new javax.swing.JLabel();
        project_name = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(45, 118, 232));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        user_name.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        user_name.setForeground(new java.awt.Color(255, 255, 255));
        user_name.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(user_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 40, 265, 20));

        back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/back.png"))); // NOI18N
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        jPanel1.add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 67, 48));

        jLabel16.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("Houer User");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(133, 29, 190, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1150, 80));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        task_number.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        task_number.setText("Task Number");
        jPanel2.add(task_number, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, 168, 34));

        completed.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        completed.setText("Completed");
        jPanel2.add(completed, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 480, 168, 34));

        type_of_project.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        type_of_project.setText("Type of Procces");
        jPanel2.add(type_of_project, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 400, 168, 34));

        project_issue.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        project_issue.setText("Project Issue");
        jPanel2.add(project_issue, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 168, 34));

        tabelOfHouers.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Project Name", "Project Issue", "Task Number", "Type of Procces"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabelOfHouers.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelOfHouersMouseClicked(evt);
            }
        });
        tabelOfHouers.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tabelOfHouersKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(tabelOfHouers);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 10, 930, 449));

        description.setColumns(20);
        description.setRows(5);
        description.setText("Description");
        jScrollPane2.setViewportView(description);

        jPanel2.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 470, 590, -1));

        user.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        user.setText("User");
        jPanel2.add(user, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 168, 34));

        project_name.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        project_name.setText("Project Name");
        jPanel2.add(project_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 168, 34));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 1150, 590));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        home = new HomeAdmin();
        home.setVisible(true);
        home.getWelcome_user().setText(user_name.getText());
        this.dispose();
    }//GEN-LAST:event_backActionPerformed

    private void tabelOfHouersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelOfHouersMouseClicked
        int selectedRow = tabelOfHouers.getSelectedRow();
        user.setText(tabelOfHouers.getValueAt(selectedRow, 0).toString());
        project_name.setText(tabelOfHouers.getValueAt(selectedRow, 1).toString());
        project_issue.setText(tabelOfHouers.getValueAt(selectedRow, 2).toString());
        task_number.setText(tabelOfHouers.getValueAt(selectedRow, 3).toString());
        type_of_project.setText(tabelOfHouers.getValueAt(selectedRow, 4).toString());
        completed.setText(tabelOfHouers.getValueAt(selectedRow, 5).toString());
        description.setText(tabelOfHouers.getValueAt(selectedRow, 6).toString());
    }//GEN-LAST:event_tabelOfHouersMouseClicked

    private void tabelOfHouersKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tabelOfHouersKeyPressed

    }//GEN-LAST:event_tabelOfHouersKeyPressed

    private void manageHouers() {

        DefaultTableModel tableModel = configTable();

        Object[] row = new Object[7];

        //Impllement The user Var
        for (int i = 0; i < hours.getAllHouerOfUsers().size(); i++) {
            row[0] = hours.getAllHouerOfUsers().get(i).getUser();
            row[1] = hours.getAllHouerOfUsers().get(i).getProject_name();
            row[2] = hours.getAllHouerOfUsers().get(i).getProject_issue();
            row[3] = hours.getAllHouerOfUsers().get(i).getTask_number();
            row[4] = hours.getAllHouerOfUsers().get(i).getType_of_procces();
            row[5] = hours.getAllHouerOfUsers().get(i).getCompleted();
            row[6] = hours.getAllHouerOfUsers().get(i).getDescription();
            tableModel.addRow(row);
        }
        tabelOfHouers.setModel(tableModel);

    }

    private DefaultTableModel configTable() {
        DefaultTableModel tableModel = new DefaultTableModel(
                new Object[][]{{}},
                new Object[]{"User", "Project Name", "Project Issue", "Task Number", "Type Of Procces", "Completed", "Description"}
        ) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }

        };
        tableModel.setRowCount(0);
        return tableModel;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(WorkesHours.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(WorkesHours.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(WorkesHours.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WorkesHours.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new WorkesHours().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private javax.swing.JLabel completed;
    private javax.swing.JTextArea description;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel project_issue;
    private javax.swing.JLabel project_name;
    private javax.swing.JTable tabelOfHouers;
    private javax.swing.JLabel task_number;
    private javax.swing.JLabel type_of_project;
    private javax.swing.JLabel user;
    private javax.swing.JLabel user_name;
    // End of variables declaration//GEN-END:variables
}
